### ISSUE TITLE
Logging Improvements

### ISSUE THREAD

**Issue by cjlucas** [cjlucas/vidfeeder#36]
Tracking ticket for various logging improvements

- [x] Add Logger TCP Backend (#38)
- [x] Add Logger formatter for handing JSON serialization (#39)
  - Add support for `context` and `event` as siblings of `metadata`
- [x] Add Log module (#40)
  - Wrapper around `Logger`
  - Interface
    - `Log.put_context(...)`
- [x] Add [vector](https://github.com/timberio/vector) to Ansible playbook (#37)
- [x] Audit and update existing log lines to support (#40)
- [x] Enable TCP backend in production (#41)

**Comment by cjlucas** [comment]
Done
